name: Python Selenium Tests

on: [push]  # Triggers this workflow on every push

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on latest Ubuntu GitHub-hosted runner

    steps:
    - uses: actions/checkout@v3  # Checkout your code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # You can pin this to 3.10 or 3.11 if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
